services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=industry_chat'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
      - 'TZ=Asia/Kolkata'
      - 'PGTZ=Asia/Kolkata'
    ports:
      - '5433:5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
volumes:
  postgres_data: